---
sidebar: sidebar 
permalink: concept_perf_general.html 
keywords: ontap select, performance 
summary: Die Leistung eines ONTAP Select Clusters kann je nach Hardwarekonfiguration variieren. 
---
= ONTAP Select Leistungsübersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Leistung eines ONTAP Select Clusters kann aufgrund der Eigenschaften der zugrunde liegenden Hardware und Konfiguration erheblich variieren. Die spezifische Hardwarekonfiguration ist der wichtigste Faktor für die Leistung einer bestimmten ONTAP Select Instanz. Hier sind einige der Faktoren, die die Leistung einer bestimmten ONTAP Select Instanz beeinflussen:

* *Kernfrequenz*. Im Allgemeinen ist eine höhere Frequenz vorzuziehen.
* *Einzelsockel im Vergleich zu Multisocket*. ONTAP Select verwendet keine Multisocket-Funktionen, aber der Hypervisor-Overhead für die Unterstützung von Multisocket-Konfigurationen ist für eine gewisse Abweichung in der Gesamtleistung verantwortlich.
* *RAID-Kartenkonfiguration und zugehöriger Hypervisor-Treiber*. Der vom Hypervisor bereitgestellte Standardtreiber muss möglicherweise durch den Treiber des Hardwareanbieters ersetzt werden.
* *Laufwerkstyp und Anzahl der Laufwerke in der/den RAID-Gruppe(n)*.
* *Hypervisor-Version und Patch-Level*.

