---
sidebar: sidebar 
permalink: concept_api_before_browser.html 
keywords: rest api, deploy rest api, rest, access browser, before you begin 
summary: Bevor Sie die Online-Dokumentationsseite „Deploy“ verwenden, sollten Sie sich über mehrere Dinge im Klaren sein. 
---
= Bevor Sie mit einem Browser auf die ONTAP Select Deploy API zugreifen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie die Online-Dokumentationsseite „Deploy“ verwenden, sollten Sie sich über mehrere Dinge im Klaren sein.



== Bereitstellungsplan

Wenn Sie API-Aufrufe im Rahmen bestimmter Bereitstellungs- oder Verwaltungsaufgaben ausführen möchten, sollten Sie einen Bereitstellungsplan erstellen. Diese Pläne können formell oder informell sein und enthalten in der Regel Ihre Ziele und die zu verwendenden API-Aufrufe. Weitere Informationen finden Sie unter Workflow-Prozesse mit der Deploy REST API.



== JSON-Beispiele und Parameterdefinitionen

Jeder API-Aufruf wird auf der Dokumentationsseite in einem einheitlichen Format beschrieben. Der Inhalt umfasst Implementierungshinweise, Abfrageparameter und HTTP-Statuscodes. Darüber hinaus können Sie Details zum JSON-Code anzeigen, der mit den API-Anfragen und -Antworten verwendet wird:

* Beispielwert: Wenn Sie bei einem API-Aufruf auf _Beispielwert_ klicken, wird eine typische JSON-Struktur für den Aufruf angezeigt. Sie können das Beispiel nach Bedarf anpassen und als Eingabe für Ihre Anfrage verwenden.
* Modell Wenn Sie auf _Modell_ klicken, wird eine vollständige Liste der JSON-Parameter mit einer Beschreibung für jeden Parameter angezeigt.




== Vorsicht beim Ausgeben von API-Aufrufen

Alle API-Vorgänge, die Sie über die Dokumentationsseite „Bereitstellen“ ausführen, sind Live-Vorgänge. Achten Sie darauf, nicht versehentlich Konfigurationen oder andere Daten zu erstellen, zu aktualisieren oder zu löschen.
