---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: Machen Sie sich zunächst mit den allgemeinen Netzwerkkonzepten vertraut, die für die ONTAP Select Umgebung gelten. Erkunden Sie anschließend die spezifischen Merkmale und Optionen der Single-Node- und Multi-Node-Cluster. 
---
= ONTAP Select Netzwerkkonzepte und -merkmale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Machen Sie sich zunächst mit den allgemeinen Netzwerkkonzepten vertraut, die für die ONTAP Select Umgebung gelten. Erkunden Sie anschließend die spezifischen Merkmale und Optionen der Single-Node- und Multi-Node-Cluster.



== Physische Vernetzung

Das physische Netzwerk unterstützt die Bereitstellung eines ONTAP Select Clusters in erster Linie durch die Bereitstellung der zugrunde liegenden Layer-2-Switching-Infrastruktur. Die Konfiguration des physischen Netzwerks umfasst sowohl den Hypervisor-Host als auch die umfassendere Switched-Network-Umgebung.



=== Host-NIC-Optionen

Jeder ONTAP Select Hypervisor-Host muss mit zwei oder vier physischen Ports konfiguriert werden. Die genaue Konfiguration hängt von mehreren Faktoren ab, darunter:

* Ob der Cluster einen oder mehrere ONTAP Select Hosts enthält
* Welches Hypervisor-Betriebssystem wird verwendet
* So wird der virtuelle Switch konfiguriert
* Ob LACP mit den Links verwendet wird oder nicht




=== Physische Switch-Konfiguration

Stellen Sie sicher, dass die Konfiguration der physischen Switches die ONTAP Select Bereitstellung unterstützt. Die physischen Switches sind in die hypervisorbasierten virtuellen Switches integriert. Die genaue Konfiguration hängt von mehreren Faktoren ab. Zu den wichtigsten Überlegungen gehören:

* Wie werden Sie die Trennung zwischen internen und externen Netzwerken aufrechterhalten?
* Werden Sie eine Trennung zwischen den Daten- und Verwaltungsnetzwerken aufrechterhalten?
* Wie werden die Layer-2-VLANs konfiguriert?




== Logische Vernetzung

ONTAP Select nutzt zwei verschiedene logische Netzwerke und trennt den Datenverkehr nach Typ. Der Datenverkehr kann sowohl zwischen den Hosts innerhalb des Clusters als auch zu den Storage-Clients und anderen Maschinen außerhalb des Clusters fließen. Die von den Hypervisoren verwalteten virtuellen Switches unterstützen das logische Netzwerk.



=== Internes Netzwerk

Bei einer Cluster-Bereitstellung mit mehreren Knoten kommunizieren die einzelnen ONTAP Select Knoten über ein isoliertes „internes“ Netzwerk. Dieses Netzwerk ist außerhalb der Knoten im ONTAP Select Cluster weder sichtbar noch verfügbar.


NOTE: Das interne Netzwerk ist nur bei einem Multi-Node-Cluster vorhanden.

Das interne Netzwerk weist die folgenden Eigenschaften auf:

* Wird zur Verarbeitung des ONTAP -Cluster-internen Datenverkehrs verwendet, einschließlich:
+
** Cluster
** Hochverfügbarkeits-Interconnect (HA-IC)
** RAID-Synchronisationsspiegel (RSM)


* Single-Layer-Two-Netzwerk basierend auf einem VLAN
* Statische IP-Adressen werden von ONTAP Select zugewiesen:
+
** Nur IPv4
** DHCP wird nicht verwendet
** Link-Local-Adresse


* Die MTU-Größe beträgt standardmäßig 9000 Bytes und kann im Bereich von 7500-9000 (einschließlich) angepasst werden.




=== Externes Netzwerk

Das externe Netzwerk verarbeitet den Datenverkehr zwischen den Knoten eines ONTAP Select Clusters und den externen Storage-Clients sowie den anderen Maschinen. Das externe Netzwerk ist Teil jeder Cluster-Bereitstellung und weist die folgenden Merkmale auf:

* Wird zur Verarbeitung von ONTAP -Verkehr verwendet, einschließlich:
+
** Daten (NFS, CIFS, iSCSI)
** Verwaltung (Cluster und Knoten; optional SVM)
** Intercluster (optional)


* Unterstützt optional VLANs:
+
** Datenportgruppe
** Verwaltungsportgruppe


* IP-Adressen, die basierend auf den Konfigurationseinstellungen des Administrators zugewiesen werden:
+
** IPv4 oder IPv6


* Die MTU-Größe beträgt standardmäßig 1500 Byte (kann angepasst werden)


Das externe Netzwerk ist mit Clustern aller Größen vorhanden.



== Netzwerkumgebung für virtuelle Maschinen

Der Hypervisor-Host bietet mehrere Netzwerkfunktionen.

ONTAP Select basiert auf den folgenden Funktionen, die über die virtuelle Maschine bereitgestellt werden:

Ports für virtuelle Maschinen:: Für ONTAP Select stehen mehrere Ports zur Verfügung. Sie werden auf Grundlage verschiedener Faktoren zugewiesen und verwendet, unter anderem aufgrund der Größe des Clusters.
Virtueller Switch:: Die virtuelle Switch-Software in der Hypervisor-Umgebung, ob vSwitch (VMware) oder Open vSwitch (KVM), verbindet die von der virtuellen Maschine bereitgestellten Ports mit den physischen Ethernet-NIC-Ports. Sie müssen für jeden ONTAP Select Host einen vSwitch entsprechend Ihrer Umgebung konfigurieren.

