---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: Sie können eine ONTAP Select Capacity Tier- oder Capacity Pool-Lizenz in einer von drei Plattformkapazitätsstufen erwerben. Diese Lizenzangebote bestimmen die Funktionen der Hosts, auf denen Sie ONTAP Select bereitstellen. 
---
= Erfahren Sie mehr über die Plattformlizenzangebote für ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine ONTAP Select Capacity Tier- oder Capacity Pool-Lizenz in den Stufen Standard, Premium oder Premium XL erwerben. Diese Lizenzangebote bestimmen die Funktionen der Hosts, auf denen Sie ONTAP Select bereitstellen.



== Was ein Plattformlizenzangebot bietet

Ein bestimmtes Lizenzangebot legt die Fähigkeiten des Hypervisor-Hosts in zwei Bereichen fest:

* Instanztyp (CPU, Speicher)
* Zusätzliche Funktionen


Die Lizenzangebote sind nach aufsteigendem Funktionsumfang von Standard bis Premium XL sortiert. Im Allgemeinen gewährt Ihnen die gewählte Lizenzoption die Funktionen dieser Stufe und aller niedrigeren Stufen. Beispielsweise bietet die Premium-Stufe sowohl die Funktionen von Premium als auch von Standard.

Die folgende Tabelle vergleicht die Funktionen der Standard-, Premium- und Premium-XL-Lizenzangebote.

[cols="25,25,25,25,25"]
|===
2+| Lizenz unterstützt ... | Standard | Prämie | Premium XL 


2+| Instanztyp | Nur Klein | Klein oder mittel | Klein, mittel oder groß 


.2+| Festplattenlaufwerke (HDD) in einem ... | Hardware-RAID-Konfiguration | Ja | Ja | Ja 


| vNAS-Konfiguration | Ja | Ja | Ja 


.3+| Solid-State-Laufwerke (SSDs) in einem ... | Hardware-RAID-Konfiguration | Nein | Ja | Ja 


| Software-RAID-Konfiguration | Nein | Ja | Ja 


| vNAS-Konfiguration | Ja | Ja | Ja 


.3+| NVMe-Laufwerke in einem ... | Hardware-RAID-Konfiguration | Nein | Nein | Ja 


| Software-RAID-Konfiguration | Nein | Nein | Ja 


| vNAS-Konfiguration | Ja | Ja | Ja 


2+| MetroCluster SDS | Nein | Ja | Ja 
|===

NOTE: Kernelbasierte virtuelle Maschinen (KVM) unterstützen den Instanztyp „large“ nicht.



== Vergleichen Sie den Hardware-Support für Plattformlizenzangebote

Die Lizenzen Standard, Premium und Premium XL unterstützen eine breite Palette an Hardware und Software. Aktuelle Informationen zu Hardware- und Softwareversionen finden Sie unterlink:https://mysupport.netapp.com/matrix/["Interoperabilitätsmatrix-Tool"^] Die

[role="tabbed-block"]
====
.Kernartikel
--
[cols="5"30"]
|===


2+| Kernartikeltyp 3+| Beschreibung 


2+| Host-Protokolle 3+| NFS, SMB/CIFS, iSCSI und NVMe über TCP 


2+| Bereitstellungsoptionen 3+| Einzelknoten Zwei-Knoten-Cluster (HA-Paar) Vier-, Sechs- oder Acht-Knoten-Cluster 


2+| Unterstützte Kapazität (pro Knoten) 3+| Bis zu 400 TB Rohdaten (ESXi und KVM) 
|===
--
.Hardware
--
[cols="5"30"]
|===


2+| Hardwaretyp 3+| Beschreibung 


2+| Instanzgröße | Klein | Medium | Groß 


2+| CPU-Familie | Intel Xeon E5-26xx v3 (Haswell) oder höher | Intel Xeon E5-26xx v3 (Haswell) oder höher | Intel Xeon E5-26xx v3 (Haswell) oder höher 


2+| ONTAP Select | 4 virtuelle CPUs (vCPUs) / 16 GB RAM | 8 vCPUs / 64 GB RAM | 16 vCPUs / 128 GB RAM 


2+| Mindestanforderungen an Host-CPU/Speicher ^1^ | 6 Kerne / 24 GB RAM | 10 Kerne / 72 GB RAM | 18 Kerne / 136 GB RAM 


2+| Netzwerk (pro Knoten) 3+| Mindestens zwei 1GbE-Ports für einen Cluster mit einem Knoten. Mindestens vier 1GbE-Ports für einen Cluster mit zwei Knoten (HA-Paar). Mindestens zwei 10GbE-Ports für einen Cluster mit vier, sechs oder acht Knoten. 
|===
^1^ Setzt zwei Kerne und 8 GB RAM für den Hypervisor voraus.

--
.Speichertyp
--
Die folgende Tabelle enthält den für den angegebenen Speicher erforderlichen Mindestlizenztyp. 

[cols="5"30"]
|===


2+| Speichertyp 3+| Beschreibung 


2+| Lizenztyp | Standard | Prämie | Premium XL 


2+| Instanzgröße | Klein | Klein und mittel | Klein, mittel und groß 


2+| Lokales DAS mit Hardware-RAID-Controller | 8 - 60 Laufwerke | 8 - 60 Laufwerke | 8 - 60 Laufwerke 


2+| Festplatte (SAS, NL-SAS, SATA) | Nicht zutreffend | 4 – 60 Laufwerke | 4 – 60 Laufwerke 


2+| SSD (SAS) | Nicht zutreffend | 4 – 60 Laufwerke (nur SSD) | 4 – 60 Laufwerke (nur SSD) 


2+| Lokales DAS mit Software-RAID | Nicht zutreffend | Anwendbar | 4 – 14 Laufwerke (nur NVMe) 


2+| Externe Arrays ^1^ 3+| Auf externen Arrays gehostete Datenspeicher sind über FC, FCoE, iSCSI und NFS verbunden (NFS wird für KVM nicht unterstützt). Diese Datenspeicher bieten hohe Verfügbarkeit und Ausfallsicherheit. 
|===
^1^ Die Unterstützung externer Array-Protokolle spiegelt die Konnektivität vernetzter Speicher wider.

--
.Software
--
[cols="5"30"]
|===


2+| Softwaretyp 3+| Beschreibung 


2+| Hypervisor-Unterstützung (VMware) 3+| VMware vSphere 9.0, VMware vSphere 8.0GA und Updates 1 bis 3, VMware vSphere 7.0GA und Updates 1 bis 3C 


2+| Hypervisor-Unterstützung (KVM)  a| 
Red Hat Enterprise Linux (RHEL) 64-Bit (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 und 8.6

Rocky Linux (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 und 8.6

*Hinweis*: Für KVM-Hypervisoren auf RHEL 10.0- und Rocky Linux 10.0-Hosts gibt es Einschränkungen im Software-RAID-Workflow. Weitere Informationen finden Sie in den folgenden Artikeln unserer Wissensdatenbank:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Warnmeldung beim Erstellen der Cluster-Hardware unter Verwendung von RHEL 10 und ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Speicherpools und Speicherdatenträger werden für SWR auf der Seite zur Clustererstellung auf Hosts mit RHEL10/Rocky 10 nicht angezeigt."^]




2+| Verwaltungssoftware 3+| NetApp Active IQ Unified Manager -Verwaltungssuite ONTAP Select Deploy Utility SnapCenter (optional) 
|===
--
====
.Ähnliche Informationen
* link:concept_lic_production.html["Erfahren Sie mehr über die Lizenztypen „Capacity Tier“ und „Capacity Pool“."]

