---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: Eigenschaften interner und externer ONTAP Select -Netzwerke. 
---
= ONTAP Select interne und externe Netzwerke
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Eigenschaften von ONTAP Select internen und externen Netzwerken.



== ONTAP Select das interne Netzwerk aus

Das interne ONTAP Select Netzwerk, das nur in der Multinode-Variante des Produkts vorhanden ist, ist für die Bereitstellung von Cluster-Kommunikation, HA-Interconnect und synchronen Replikationsdiensten für den ONTAP Select Cluster verantwortlich. Dieses Netzwerk umfasst die folgenden Ports und Schnittstellen:

* *e0c, e0d.* Hosting von Cluster-Netzwerk-LIFs
* *e0e.* Host des RSM LIF
* *e0f.* Hosten des HA-Interconnect-LIF


Der Durchsatz und die Latenz dieses Netzwerks sind entscheidend für die Leistung und Ausfallsicherheit des ONTAP Select Clusters. Die Netzwerkisolierung ist für die Clustersicherheit und zur Trennung der Systemschnittstellen vom übrigen Netzwerkverkehr erforderlich. Daher darf dieses Netzwerk ausschließlich vom ONTAP Select Cluster verwendet werden.


NOTE: Die Verwendung des internen Netzwerks „Select“ für anderen Datenverkehr als den Cluster-Datenverkehr „Select“, z. B. Anwendungs- oder Verwaltungsdatenverkehr, wird nicht unterstützt. Im internen ONTAP -VLAN dürfen sich keine anderen VMs oder Hosts befinden.

Netzwerkpakete, die das interne Netzwerk durchlaufen, müssen sich in einem dedizierten VLAN-getaggten Layer-2-Netzwerk befinden. Dies kann durch Ausführen einer der folgenden Aufgaben erreicht werden:

* Zuweisen einer VLAN-getaggten Portgruppe zu den internen virtuellen NICs (e0c bis e0f) (VST-Modus)
* Verwenden des nativen VLAN, das vom Upstream-Switch bereitgestellt wird, wenn das native VLAN nicht für anderen Datenverkehr verwendet wird (weisen Sie eine Portgruppe ohne VLAN-ID zu, d. h. EST-Modus).


In allen Fällen erfolgt die VLAN-Kennzeichnung für den internen Netzwerkverkehr außerhalb der ONTAP Select VM.


NOTE: Es werden nur ESX-Standard- und verteilte vSwitches unterstützt. Andere virtuelle Switches oder direkte Verbindungen zwischen ESX-Hosts werden nicht unterstützt. Das interne Netzwerk muss vollständig geöffnet sein; NAT oder Firewalls werden nicht unterstützt.

Innerhalb eines ONTAP Select Clusters werden interner und externer Datenverkehr mithilfe virtueller Layer-2-Netzwerkobjekte, sogenannter Portgruppen, getrennt. Die korrekte vSwitch-Zuweisung dieser Portgruppen ist äußerst wichtig, insbesondere für das interne Netzwerk, das für die Bereitstellung von Cluster-, HA-Interconnect- und Mirror-Replication-Diensten zuständig ist. Unzureichende Netzwerkbandbreite für diese Netzwerkports kann zu Leistungseinbußen führen und sogar die Stabilität des Clusterknotens beeinträchtigen. Daher erfordern Cluster mit vier, sechs und acht Knoten eine 10-Gbit-Konnektivität im internen ONTAP Select Netzwerk; 1-Gbit-NICs werden nicht unterstützt. Kompromisse beim externen Netzwerk sind jedoch möglich, da die Begrenzung des eingehenden Datenflusses zu einem ONTAP Select Cluster dessen Zuverlässigkeit nicht beeinträchtigt.

Ein Cluster mit zwei Knoten kann entweder vier 1-Gbit-Ports für den internen Datenverkehr oder einen einzelnen 10-Gbit-Port anstelle der zwei 10-Gbit-Ports verwenden, die der Cluster mit vier Knoten benötigt. In einer Umgebung, in der der Server aufgrund der Bedingungen nicht mit vier 10-Gbit-NIC-Karten ausgestattet werden kann, können zwei 10-Gbit-NIC-Karten für das interne Netzwerk und zwei 1-Gbit-NICs für das externe ONTAP Netzwerk verwendet werden.



=== Interne Netzwerkvalidierung und Fehlerbehebung

Das interne Netzwerk in einem Multinode-Cluster kann mithilfe der Netzwerkkonnektivitätsprüfung validiert werden. Diese Funktion kann über die Deploy CLI aufgerufen werden, die ausgeführt wird. `network connectivity-check start` Befehl.

Führen Sie den folgenden Befehl aus, um die Ausgabe des Tests anzuzeigen:

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
Dieses Tool ist nur für die Fehlerbehebung im internen Netzwerk eines Multi-Node-Select-Clusters nützlich. Das Tool sollte nicht zur Fehlerbehebung bei Single-Node-Clustern (einschließlich vNAS-Konfigurationen), der ONTAP Deploy-to- ONTAP Select Konnektivität oder clientseitigen Konnektivitätsproblemen verwendet werden.

Der Cluster-Erstellungsassistent (Teil der ONTAP Deploy UI) beinhaltet die interne Netzwerkprüfung als optionalen Schritt bei der Erstellung von Multinode-Clustern. Angesichts der wichtigen Rolle des internen Netzwerks in Multinode-Clustern verbessert die Integration dieses Schritts in den Cluster-Erstellungs-Workflow die Erfolgsquote von Cluster-Erstellungsvorgängen.

Ab ONTAP Deploy 2.10 kann die vom internen Netzwerk verwendete MTU-Größe zwischen 7.500 und 9.000 eingestellt werden. Mit dem Netzwerkkonnektivitätsprüfer können Sie die MTU-Größe auch zwischen 7.500 und 9.000 testen. Der Standard-MTU-Wert entspricht dem Wert des virtuellen Netzwerk-Switches. Dieser Standardwert muss durch einen kleineren Wert ersetzt werden, wenn in der Umgebung ein Netzwerk-Overlay wie VXLAN vorhanden ist.



== ONTAP Select

Das externe ONTAP Select Netzwerk ist für die gesamte ausgehende Kommunikation des Clusters verantwortlich und ist daher sowohl in Einzelknoten- als auch in Multiknotenkonfigurationen vorhanden. Obwohl dieses Netzwerk nicht die streng definierten Durchsatzanforderungen des internen Netzwerks erfüllt, sollte der Administrator darauf achten, keine Netzwerkengpässe zwischen dem Client und der ONTAP VM zu verursachen, da Leistungsprobleme fälschlicherweise als ONTAP Select Probleme interpretiert werden könnten.


NOTE: Ähnlich wie interner Datenverkehr kann externer Datenverkehr auf der vSwitch-Ebene (VST) und auf der externen Switch-Ebene (EST) markiert werden. Darüber hinaus kann der externe Datenverkehr von der ONTAP Select VM selbst in einem als VGT bezeichneten Prozess markiert werden. Weitere Informationen Siehe den Abschnittlink:concept_nw_data_mgmt_separation.html["Trennung von Daten- und Verwaltungsverkehr"] für weitere Einzelheiten.

Die folgende Tabelle zeigt die wichtigsten Unterschiede zwischen den internen und externen Netzwerken von ONTAP Select .

*Kurzreferenz zu internen und externen Netzwerken*

[cols="3*"]
|===
| Beschreibung | Internes Netzwerk | Externes Netzwerk 


| Netzwerkdienste | Cluster HA/IC RAID SyncMirror (RSM) | Datenverwaltung Intercluster (SnapMirror und SnapVault) 


| Netzwerkisolation | Erforderlich | Optional 


| Framegröße (MTU) | 7.500 bis 9.000 | 1.500 (Standard) 9.000 (unterstützt) 


| IP-Adresszuweisung | Automatisch generiert | Benutzerdefiniert 


| DHCP-Unterstützung | Nein | Nein 
|===


=== NIC-Teaming

Um sicherzustellen, dass die internen und externen Netzwerke über die erforderliche Bandbreite und Ausfallsicherheit für hohe Leistung und Fehlertoleranz verfügen, wird die Teambildung physischer Netzwerkadapter empfohlen. Zwei-Knoten-Clusterkonfigurationen mit einer einzelnen 10-Gbit-Verbindung werden unterstützt. NetApp empfiehlt jedoch die Nutzung von NIC-Teaming sowohl im internen als auch im externen Netzwerk des ONTAP Select Clusters.



=== MAC-Adressgenerierung

Die allen ONTAP Select Netzwerkports zugewiesenen MAC-Adressen werden automatisch vom mitgelieferten Bereitstellungsprogramm generiert. Das Dienstprogramm verwendet eine plattformspezifische, organisatorisch eindeutige Kennung (OUI) für NetApp , um Konflikte mit FAS Systemen zu vermeiden. Eine Kopie dieser Adresse wird anschließend in einer internen Datenbank innerhalb der ONTAP Select Installations-VM (ONTAP Deploy) gespeichert, um eine versehentliche Neuzuweisung bei zukünftigen Knotenbereitstellungen zu verhindern. Der Administrator sollte die zugewiesene MAC-Adresse eines Netzwerkports zu keinem Zeitpunkt ändern.
