---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: ONTAP Select eignet sich aufgrund der inhärenten Flexibilität, die durch die Hypervisor-Virtualisierung bereitgestellt wird, für verschiedene Arten von Anwendungen. 
---
= ONTAP Select Geschäftsanforderungen und Nutzungsszenarien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select eignet sich aufgrund der inhärenten Flexibilität, die durch die Hypervisor-Virtualisierung bereitgestellt wird, für verschiedene Arten von Anwendungen.



== Einsatz

Auf einer hohen Ebene können Sie ONTAP Select hinsichtlich der Arbeitslast auf den Hypervisor-Hostservern auf zwei verschiedene Arten bereitstellen.



=== Dedizierte Bereitstellung

Beim dedizierten Bereitstellungsmodell wird eine einzelne Instanz von ONTAP Select auf dem Hostserver ausgeführt. Auf demselben Hypervisor-Host werden keine weiteren wichtigen Verarbeitungsvorgänge ausgeführt.



=== Kollokierte Bereitstellung

Beim Colocation-Bereitstellungsmodell teilt sich ONTAP Select den Host mit anderen Workloads. Insbesondere gibt es zusätzliche virtuelle Maschinen, auf denen typischerweise Rechenanwendungen ausgeführt werden. Diese Rechenlasten befinden sich lokal im ONTAP Select Cluster. Dieses Modell unterstützt spezielle Anwendungs- und Bereitstellungsanforderungen. Wie beim dedizierten Bereitstellungsmodell muss jede virtuelle ONTAP Select Maschine auf einem separaten und dedizierten Hypervisor-Host ausgeführt werden.



== Storage

ONTAP Select kann je nach Ihren Geschäftsanforderungen als primärer oder sekundärer Speicher verwendet werden.



=== Primärspeicher

In bestimmten Fällen können Sie ONTAP Select als primäre Speicherplattform einsetzen. Diese Implementierungsarten variieren und hängen von den Workload-Eigenschaften der Anwendungen sowie Ihren Geschäftszielen ab.



=== Notfallwiederherstellung und Sekundärspeicher

Mit ONTAP Select können Sie zusätzlichen Speicher implementieren und so Ihre primären Speicherkapazitäten erweitern. Der zusätzliche Speicher kann zur Unterstützung der Disaster Recovery-Bemühungen und Datensicherungspläne Ihres Unternehmens eingesetzt werden.



== Entwicklung und Tests

Bei der Bereitstellung verschiedener Anwendungen in Ihrem Unternehmen können Sie ONTAP Select als integralen Bestandteil des gesamten Anwendungsentwicklungs- und Testprozesses nutzen. Beispielsweise benötigen Sie möglicherweise temporären Speicher für Testeingabe- oder -ausgabedaten. Die Dauer solcher Bereitstellungen kann je nach Anwendungseigenschaften und -anforderungen variieren.
