---
sidebar: sidebar 
permalink: concept_api_how_access.html 
keywords: rest api, deploy rest api, rest, access, accessing, how to access 
summary: Aufgrund der inhärenten Flexibilität von REST-Webdiensten kann auf die ONTAP Select Deploy API auf verschiedene Arten zugegriffen werden. 
---
= So greifen Sie auf die ONTAP Select Deploy API zu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aufgrund der inhärenten Flexibilität von REST-Webdiensten kann auf die ONTAP Select Deploy API auf verschiedene Arten zugegriffen werden.


NOTE: Die in ONTAP Select Deploy enthaltene REST-API erhält eine Versionsnummer. Die API-Versionsnummer ist unabhängig von der Deploy-Versionsnummer. Das ONTAP Select 9.17.1 Deploy-Verwaltungsprogramm beinhaltet Version 3 der REST-API.



== Native Benutzeroberfläche des Bereitstellungsprogramms

Der primäre Zugriff auf die API erfolgt über die ONTAP Select Deploy-Webbenutzeroberfläche. Der Browser ruft die API auf und formatiert die Daten entsprechend dem Design der Benutzeroberfläche neu. Sie können auch über die Befehlszeilenschnittstelle des Deploy-Dienstprogramms auf die API zugreifen.



== ONTAP Select Deploy Online-Dokumentationsseite

Die Online-Dokumentationsseite von ONTAP Select Deploy bietet einen alternativen Zugriffspunkt bei Verwendung eines Browsers. Neben der Möglichkeit, einzelne API-Aufrufe direkt auszuführen, enthält die Seite auch eine detaillierte Beschreibung der API, einschließlich Eingabeparametern und weiteren Optionen für jeden Aufruf. Die API-Aufrufe sind in verschiedene Funktionsbereiche oder Kategorien unterteilt.



== Benutzerdefiniertes Programm

Sie können mit verschiedenen Programmiersprachen und Tools auf die Deploy-API zugreifen. Beliebte Optionen sind Python, Java und cURL. Ein Programm, Skript oder Tool, das die API nutzt, fungiert als REST-Webservice-Client. Die Verwendung einer Programmiersprache ermöglicht Ihnen ein besseres Verständnis der API und bietet die Möglichkeit, ONTAP Select Bereitstellungen zu automatisieren.
