---
sidebar: sidebar 
permalink: reference_chk_deploy_req_info.html 
keywords: ontap select, deploy, pre-installation, vmware 
summary: Bevor Sie das Deploy-Verwaltungsprogramm in einer VMware-Umgebung installieren, überprüfen Sie die grundlegenden Anforderungen und bereiten Sie sich auf eine erfolgreiche Bereitstellung vor. 
---
= Erforderliche Informationen für die Installation des ONTAP Select Deploy-Dienstprogramms
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie das Deploy-Verwaltungsprogramm in einer Hypervisor-Umgebung installieren, überprüfen Sie die erforderlichen Konfigurationsinformationen und optionalen Netzwerkkonfigurationsinformationen, um eine erfolgreiche Bereitstellung vorzubereiten.



== Erforderliche Konfigurationsinformationen

Im Rahmen Ihrer Bereitstellungsplanung sollten Sie die erforderlichen Konfigurationsinformationen ermitteln, bevor Sie das Verwaltungsdienstprogramm ONTAP Select Deploy installieren.

[cols="40,60"]
|===
| Erforderliche Informationen | Beschreibung 


| Name der bereitgestellten virtuellen Maschine | Für die virtuelle Maschine zu verwendende Kennung. 


| Name des Hypervisor-Hosts | Kennung für den VMware ESXi- oder KVM-Hypervisor-Host, auf dem das Bereitstellungsprogramm installiert ist. 


| Name des Datenspeichers | Kennung für den Hypervisor-Datenspeicher, der die Dateien der virtuellen Maschine enthält (ungefähr 40 GB sind erforderlich). 


| Netzwerk für die virtuelle Maschine | Kennung für das Netzwerk, mit dem die virtuelle Bereitstellungsmaschine verbunden ist. 
|===


== Optionale Netzwerkkonfigurationsinformationen

Die virtuelle Maschine „Deploy“ wird standardmäßig per DHCP konfiguriert. Bei Bedarf können Sie die Netzwerkschnittstelle für die virtuelle Maschine jedoch auch manuell konfigurieren.

[cols="35,65"]
|===
| Netzwerkinformationen | Beschreibung 


| Hostname | Kennung des Hostcomputers. 


| Host-IP-Adresse | Statische IPv4-Adresse des Hostcomputers. 


| Subnetzmaske | Subnetzmaske, basierend auf dem Netzwerk, zu dem die virtuelle Maschine gehört. 


| Tor | Standard-Gateway oder -Router. 


| Primärer DNS-Server | Primärer Domänennamenserver. 


| Sekundärer DNS-Server | Sekundärer Domänennamenserver. 


| Suchdomänen | Liste der zu verwendenden Suchdomänen. 
|===