---
sidebar: sidebar 
permalink: reference_initial_state.html 
keywords: install, installing, initial state, cluster initial state 
summary: Sie sollten den Anfangszustand eines Clusters nach seiner Bereitstellung kennen und den Cluster nach Bedarf für Ihre Umgebung konfigurieren. 
---
= Ausgangszustand des ONTAP Select Clusters nach der Bereitstellung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten den Anfangszustand eines Clusters nach seiner Bereitstellung kennen und den Cluster nach Bedarf für Ihre Umgebung konfigurieren.

Ein ONTAP Select Cluster weist nach seiner Erstellung mehrere Eigenschaften auf.


NOTE: Das Einschränken von Rollen und Berechtigungen für das ONTAP Administratorkonto kann die Fähigkeit von ONTAP Select Deploy zur Verwaltung des Clusters einschränken. Weitere Informationen finden Sie im Artikel der Wissensdatenbank.link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/OTS_Deploy_cluster_refresh_fails_with_error%3A_ONTAPSelectSysCLIVersionFailed_zapi_returned_bad_status_0%3A_None["Die Aktualisierung des OTS-Bereitstellungsclusters schlägt mit einem Fehler fehl"^] Die

.LIFs
Es werden zwei Arten von kundenspezifischen LIFs zugewiesen:

* Clusterverwaltung (eine pro Cluster)
* Knotenverwaltung (eine pro Knoten)



NOTE: Ein Cluster mit mehreren Knoten verfügt über ein internes Netzwerk mit automatisch generierten LIFs.

.SVMs
Drei SVMs sind aktiv:

* Administrator-SVM
* Knoten-SVM
* System (Cluster) SVM



NOTE: Daten-SVMs werden nicht im Rahmen der ONTAP Select -Clusterbereitstellung erstellt. Sie müssen nach der Bereitstellung vom Clusteradministrator erstellt werden. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/nfs-config/create-svms-data-access-task.html["Erstellen einer SVM"^] Die

.Aggregate
Das Stammaggregat wird erstellt.

.Features
Alle Funktionen sind lizenziert und verfügbar. Sowohl SnapLock als auch FabricPool erfordern separate Lizenzen.

.Ähnliche Informationen
* link:https://docs.netapp.com/us-en/ontap/system-admin/types-svms-concept.html["In einem Cluster enthaltene SVM-Typen"^]
* link:reference_lic_ontap_features.html["ONTAP -Funktionen standardmäßig aktiviert"]

