---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: Es gibt mehrere allgemeine Anforderungen, die Sie bei der Planung der Installation des ONTAP Select Deploy-Verwaltungsprogramms berücksichtigen sollten. 
---
= Allgemeine Anforderungen und Planung für ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es gibt mehrere allgemeine Anforderungen, die Sie bei der Planung der Installation des ONTAP Select Deploy-Verwaltungsprogramms berücksichtigen sollten.



== Koppeln des Deploy-Dienstprogramms mit den ONTAP Select Clustern

Beim Koppeln einer Instanz des Deploy-Dienstprogramms mit den ONTAP Select -Clustern stehen Ihnen mehrere Optionen zur Verfügung.


NOTE: In allen Bereitstellungsszenarien können ein einzelner ONTAP Select Cluster und die darin enthaltenen Knoten nur von einer Instanz des Deploy-Verwaltungsprogramms verwaltet werden. Ein Cluster kann nicht von zwei oder mehr verschiedenen Instanzen des Deploy-Dienstprogramms verwaltet werden.

.Eine Instanz des Dienstprogramms für jeden ONTAP Select Cluster
Sie können jeden ONTAP Select Cluster mit einer dedizierten Instanz des Deploy-Dienstprogramms bereitstellen und verwalten. Mit dieser Eins-zu-eins-Konfiguration besteht eine klare Trennung zwischen den einzelnen Dienstprogramm-Cluster-Paarungen. Diese Konfiguration bietet ein hohes Maß an Isolation mit kleineren Fehlerdomänen.

.Eine Instanz des Dienstprogramms für mehrere ONTAP Select -Cluster
Sie können mehrere ONTAP Select Cluster in Ihrem Unternehmen mit einer einzigen Instanz des Deploy-Dienstprogramms bereitstellen und verwalten. Bei dieser Eins-zu-viele-Konfiguration werden alle Verarbeitungs- und Konfigurationsdaten von derselben Instanz des Deploy-Dienstprogramms verwaltet.


NOTE: Eine Instanz des Deploy-Dienstprogramms kann bis zu 400 ONTAP Select Knoten oder 100 Cluster verwalten.



== Anforderungen an die KVM-Umgebung

Bevor Sie das Deploy-Verwaltungsprogramm in einer KVM-Hypervisorumgebung installieren, sollten Sie die grundlegenden Anforderungen überprüfen und die Bereitstellung vorbereiten.

.Voraussetzungen und Einschränkungen für eine Bereitstellung
Es gibt verschiedene Anforderungen und Einschränkungen, die Sie bei der Installation des Dienstprogramms ONTAP Select Deploy in einer KVM-Umgebung berücksichtigen sollten.

.Hardwareanforderungen für Linux-KVM-Hostserver
Ihr Linux KVM-Hypervisor-Host muss mehrere Mindestressourcenanforderungen erfüllen. Stellen Sie sicher, dass die Hosts, auf denen ONTAP Select bereitgestellt wird, die folgenden grundlegenden Anforderungen erfüllen:

* Linux-Server:
+
** Die Hardware und Software muss 64-Bit sein
** Der Server muss dieselben unterstützten Versionen einhalten, die für einen ONTAP Select Knoten definiert sind


* Virtuelle CPUs (2)
* Virtueller Speicher (4 GB)
* Speicher (40 GB)
* „Dynamic Host Configuration Protocol (DHCP) ist aktiviert (Sie können auch eine statische IP-Adresse zuweisen)


.Netzwerkkonnektivität
Überprüfen Sie, ob die Netzwerkschnittstelle „Deploy Virtual Machine“ konfiguriert ist und eine Verbindung zu den von ihr verwalteten ONTAP Select Hosts herstellen kann.

.Unterstützung für IP-Version 4
ONTAP Select Deploy unterstützt nur IP-Version 4 (IPv4). IP-Version 6 (IPv6) wird nicht unterstützt. Diese Einschränkung wirkt sich wie folgt auf ONTAP Select aus:

* Sie müssen dem Verwaltungs-LIF der Bereitstellungs-VM eine IPv4-Adresse zuweisen.
* Durch die Bereitstellung können keine ONTAP Select Knoten erstellt werden, die für die Verwendung von IPv6 auf den ONTAP LIFs konfiguriert sind.




== Erforderliche Konfigurationsinformationen

Im Rahmen Ihrer Bereitstellungsplanung sollten Sie die erforderlichen Konfigurationsinformationen ermitteln, bevor Sie das Verwaltungsdienstprogramm ONTAP Select Deploy installieren.

.Name der Bereitstellungs-VM
Der für die VM zu verwendende Name.

.Name des Linux KVM-Hosts
Der Linux-KVM-Host, auf dem das Bereitstellungsprogramm installiert ist.

.Name des Speicherpools
Der Speicherpool, der die VM-Dateien enthält (ungefähr 40 GB werden benötigt).

.Netzwerk für die VM
Das Netzwerk, mit dem die Deploy-VM verbunden ist.



== Optionale Netzwerkkonfigurationsinformationen

Die Bereitstellungs-VM wird standardmäßig per DHCP konfiguriert. Bei Bedarf können Sie die Netzwerkschnittstelle für die VM jedoch manuell konfigurieren.

.Hostname
Der Name des Hosts.

.Host-IP-Adresse
Die statische IPv4-Adresse.

.Subnetzmaske
Die Subnetzmaske, die auf dem Netzwerk basiert, zu dem die VM gehört.

.Tor
Das Standard-Gateway oder der Standard-Router.

.Primärer DNS-Server
Der primäre Domänennamenserver.

.Sekundärer DNS-Server
Der sekundäre Domänennamenserver.

.Suchdomänen
Die zu verwendenden Suchdomänen.



== Authentifizierung über den Anmeldeinformationsspeicher

Der Anmeldeinformationsspeicher von ONTAP Select Deploy ist eine Datenbank mit Kontoinformationen. Deploy verwendet die Kontoanmeldeinformationen zur Hostauthentifizierung im Rahmen der Clustererstellung und -verwaltung. Sie sollten wissen, wie der Anmeldeinformationsspeicher im Rahmen der Planung einer ONTAP Select Bereitstellung verwendet wird.


NOTE: Die Kontoinformationen werden mithilfe des AES-Verschlüsselungsalgorithmus und des SHA-256-Hashing-Algorithmus sicher in der Datenbank gespeichert.

.Arten von Anmeldeinformationen
Die folgenden Arten von Anmeldeinformationen werden unterstützt:

* Host Wird verwendet, um einen Hypervisor-Host im Rahmen der Bereitstellung eines ONTAP Select Knotens direkt auf VMware ESXi zu authentifizieren
* vCenter Wird verwendet, um einen vCenter-Server im Rahmen der Bereitstellung eines ONTAP Select Knotens auf ESXi zu authentifizieren, wenn der Host von VMware vCenter verwaltet wird


.Zugang
Der Zugriff auf den Anmeldeinformationsspeicher erfolgt intern im Rahmen normaler Verwaltungsaufgaben mit Deploy, z. B. beim Hinzufügen eines Hypervisor-Hosts. Sie können den Anmeldeinformationsspeicher auch direkt über die Deploy-Webbenutzeroberfläche und die CLI verwalten.
