---
sidebar: sidebar 
permalink: reference_host_modify_command.html 
keywords: host modify, command, syntax, host management server 
summary: Mit dem Befehl „Host Modify“ können Sie einen Host-Management-Server mit dieser Instanz von ONTAP Select Deploy ändern. 
---
= Ändern Sie einen Host-Management-Server für ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die `host modify` Befehl zum Ändern eines Host-Management-Servers mit dieser ONTAP Select Deploy.



== Syntax

`host modify [-help] [-foreground] -name _name_ -mgmt-server _management_server_ [-username _username_]`



== Erforderliche Parameter

[cols="35,65"]
|===


| Parameter | Beschreibung 


 a| 
`-name _name_`
 a| 
Die IP-Adresse oder der FQDN des Hosts, den Sie ändern möchten.



 a| 
`-mgmt-server _management_server_`
 a| 
Die IP-Adresse oder der FQDN des Host-Management-Servers, der auf dem Host eingerichtet werden soll. Geben Sie "-" (Bindestrich) an, um den Management-Server vom Host zu entfernen. Die Anmeldeinformationen für diesen Verwaltungsserver müssen hinzugefügt werden, bevor dieser Host registriert wird. `credential add` Befehl.

|===


== Optionale Parameter

[cols="35,65"]
|===


| Parameter | Beschreibung 


 a| 
`-help`
 a| 
Zeigt die Hilfemeldung an.



 a| 
`-foreground`
 a| 
Dieser Parameter steuert das Verhalten lang andauernder Befehle. Ist dieser Parameter gesetzt, wird der Befehl im Vordergrund ausgeführt und Ereignismeldungen zum Vorgang werden angezeigt, sobald sie auftreten.



 a| 
`-username _username_`
 a| 
Der Benutzername, der Zugriff auf diesen Host hat. Dies ist nur erforderlich, wenn der Host nicht von einem Verwaltungsserver verwaltet wird (d. h. ein von einem vCenter verwalteter ESX-Host).

|===