---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select bietet volle Unterstützung für die meisten ONTAP -Funktionen. Viele der ONTAP -Funktionen werden bei der Bereitstellung eines Clusters automatisch für jeden Knoten lizenziert. Für einige Funktionen ist jedoch eine separate Lizenz erforderlich. 
---
= ONTAP Select Unterstützung für ONTAP -Funktionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select unterstützt die meisten ONTAP Funktionen. Viele der ONTAP -Funktionen werden bei der Bereitstellung eines Clusters automatisch für jeden Knoten lizenziert. Für einige Funktionen ist jedoch eine separate Lizenz erforderlich.


NOTE: ONTAP -Funktionen mit hardwarespezifischen Abhängigkeiten werden von ONTAP Select im Allgemeinen nicht unterstützt.



[[ontap-features-automatically-enabled-by-default]]
== ONTAP -Funktionen sind standardmäßig automatisch aktiviert

Die folgenden ONTAP -Funktionen werden mit ONTAP Select unterstützt und standardmäßig lizenziert:

* Autonomous Ransomware Protection (ARP) (manuelle Updates)
* CIFS
* Deduplizierung und Komprimierung
* FlexCache
+
Es gibt Einschränkungen bei der Unterstützung von FlexCache Write-Back mit ONTAP Select. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap-select/concept_ots_overview.html#flexcache-write-back-with-ontap-select["FlexCache Write-Back mit ONTAP Select"^].

* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption (nur Länder ohne Einschränkungen)
* NFS
* NVMe über TCP
* ONTAP -Multitenancy-Funktion
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock Select ist die Implementierung von ONTAP SnapLock, die für ONTAP Select entwickelt wurde und SnapLock Enterprise umfasst. Es umfasst nicht SnapLock Compliance.

+
Erfahren Sie mehr überlink:https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLock"^]

* SnapMirror
* SnapRestore
* SnapVault
* Notfallwiederherstellung von Storage-VMs (SVM DR)
+

NOTE: ONTAP Select unterstützt SVM DR sowohl als Quelle als auch als Ziel mit maximal 16 Beziehungen. Die SVM DR-Unterstützung ist auf die Verwendung der Quell- ONTAP Version bis Version +2 beschränkt. Beispielsweise kann die Quelle von ONTAP Select 9.12.1 eine Verbindung zu den Ziel ONTAP Versionen 9.12.1, 9.13.1 oder 9.14.1 herstellen.





[[ontap-features-that-are-separately-licensed]]
== ONTAP -Funktionen, die separat lizenziert werden

Sie benötigen eine separate Lizenz für jede ONTAP Funktion, die nicht standardmäßig aktiviert ist, einschließlich:

* FabricPool
* MetroCluster SDS (ONTAP Select Premium-Lizenzangebot)
* SnapMirror Cloud
+
Sie müssen link:https://mysupport.netapp.com/site/help["Öffnen Sie einen nicht-technischen Supportfall"^] eine SnapMirror Cloud-Lizenz erwerben.

+
Erfahren Sie mehr überlink:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["SnapMirror Cloud-Backups in Objektspeicher"^]



[NOTE]
====
* Für ONTAP Select 9.16.1 und früher ist SnapLock Select (einschließlich manipulationssicherer Snapshot-Sperrung) über die link:https://mysupport.netapp.com/site/["NetApp Support Site"^] verfügbar.
* SnapLock Compliance wird für ONTAP Select nicht unterstützt.
* Sie benötigen keine FabricPool -Lizenz, wenn Sie StorageGRID verwenden.


====
.Ähnliche Informationen
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Vergleich von ONTAP Select und ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAP Master-Lizenzschlüssel"^]

