---
sidebar: sidebar 
permalink: task_adm_resize.html 
keywords: administer, administering, web, resizing nodes, resizing 
summary: Nach der Bereitstellung eines ONTAP Select Clusters können Sie den Hypervisor-Instanztyp der Knoten mithilfe des Deploy-Verwaltungsprogramms aktualisieren. 
---
= Ändern Sie die Größe der ONTAP Select Clusterknoten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach der Bereitstellung eines ONTAP Select Clusters können Sie den Hypervisor-Instanztyp der Knoten mithilfe des Deploy-Verwaltungsprogramms aktualisieren.


NOTE: Sie können die Größenänderung der Clusterknoten durchführen, wenn Sie das Lizenzmodell „Capacity Tiers“ und das Lizenzmodell „Capacity Pools“ verwenden.


NOTE: Die Größenänderung auf den großen Instanztyp wird nur auf ESXi unterstützt.

.Bevor Sie beginnen
Der Cluster muss sich im Online-Status befinden.

.Informationen zu diesem Vorgang
Diese Aufgabe beschreibt die Verwendung der Deploy-Webbenutzeroberfläche. Sie können die Größe der Instanz auch über die Deploy-CLI ändern. Unabhängig von der verwendeten Oberfläche kann die für die Größenänderung benötigte Zeit je nach verschiedenen Faktoren erheblich variieren und längere Zeit in Anspruch nehmen. Die Größe eines Knotens kann nur auf eine größere Größe geändert werden.

.Schritte
. Sign in mit dem Administratorkonto bei der Web-Benutzeroberfläche des Bereitstellungsdienstprogramms an.
. Klicken Sie oben auf der Seite auf die Registerkarte *Cluster* und wählen Sie den gewünschten Cluster aus der Liste aus.
. Klicken Sie auf der Clusterdetailseite auf das Zahnradsymbol rechts auf der Seite und wählen Sie *Instanzgröße ändern*.
. Wählen Sie den *Instanztyp* aus, geben Sie die ONTAP -Anmeldeinformationen ein und klicken Sie dann auf *Ändern*.


.Nach Abschluss
Sie müssen warten, bis der Größenänderungsvorgang abgeschlossen ist.
