---
sidebar: sidebar 
permalink: task_cli_signing_in.html 
keywords: administer, administering, cli, deploy, sign in, signing in 
summary: Sie müssen sich per SSH bei der Deploy-Verwaltungsshell anmelden. Nach der Anmeldung können Sie CLI-Befehle ausführen, um einen ONTAP Select Cluster zu erstellen und die zugehörigen Verwaltungsverfahren durchzuführen. 
---
= Sign in mit SSH bei ONTAP Select Deploy an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie müssen sich per SSH bei der Deploy-Verwaltungsshell anmelden. Nach der Anmeldung können Sie CLI-Befehle ausführen, um einen ONTAP Select Cluster zu erstellen und die zugehörigen Verwaltungsverfahren durchzuführen.

.Bevor Sie beginnen
Sie benötigen das aktuelle Kennwort für das Deploy-Administratorkonto (admin). Wenn Sie sich zum ersten Mal anmelden und vCenter zur Installation der virtuellen Deploy-Maschine verwendet haben, sollten Sie das bei der Installation festgelegte Kennwort verwenden.

.Schritte
. Sign in . Beispiel:
+
`ssh admin@<10.235.82.22>`

. Wenn Sie sich zum ersten Mal anmelden und Deploy nicht mithilfe des mit vCenter verfügbaren Assistenten installiert haben, geben Sie bei entsprechender Aufforderung die folgenden Konfigurationsinformationen ein:
+
** Neues Passwort für das Administratorkonto (erforderlich)
** Firmenname (erforderlich)
** Proxy-URL (optional)


. Geben Sie *?* ein und drücken Sie die *Eingabetaste*, um eine Liste der verfügbaren Management-Shell-Befehle anzuzeigen.

