---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Sie können ein ONTAP Select-Image zu Ihrer Instanz des Deploy-Verwaltungsprogramms hinzufügen. Nach der Installation des Images können Sie es beim Bereitstellen eines ONTAP Select Clusters verwenden. 
---
= Fügen Sie ein ONTAP Select Image zur Bereitstellung hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein ONTAP Select-Image zu Ihrer Instanz des Deploy-Verwaltungsprogramms hinzufügen. Nach der Installation des Images können Sie es beim Bereitstellen eines ONTAP Select Clusters verwenden.

.Bevor Sie beginnen
Bevor Sie neue ONTAP Select Images zu Deploy hinzufügen, sollten Sie zunächst alle nicht benötigten Images entfernen.


NOTE: Sie sollten nur ein ONTAP Select Image mit einer Version hinzufügen, die älter ist als die Originalversion, die in Ihrer Instanz des Deploy-Dienstprogramms enthalten ist. Das Hinzufügen neuerer Versionen von ONTAP Select , sobald diese von NetApp verfügbar sind, wird nicht unterstützt.



== Schritt 1: Installationsabbild herunterladen

Um ein ONTAP Select Image zu einer Instanz des Deploy-Dienstprogramms hinzuzufügen, müssen Sie das Installationsimage von der NetApp Support-Site herunterladen. Das ONTAP Select Installationsimage ist als einzelne komprimierte Datei formatiert.

.Schritte
. Greifen Sie mit einem Webbrowser auf die NetApp Support Site zu und wählen Sie *Support Quick Links* aus.
. Wählen Sie unter *Top Tasks* *Download Software* aus und melden Sie sich auf der Website an.
. Wählen Sie *Find your product* aus.
. Scrollen Sie nach unten und wählen Sie *ONTAP Select* aus.
. Unter *Other Available Select Software* wählen Sie *Deploy Upgrade, Node Upgrade, Image Install*.
. Wählen Sie die gewünschte Version des Upgrade-Pakets aus.
. Lesen Sie die End User License Agreement (EULA) und klicken Sie auf *Accept & Continue*.
. Wählen Sie das passende Paket aus und laden Sie es herunter, und beantworten Sie alle Eingabeaufforderungen entsprechend Ihrer Umgebung.




== Schritt 2: Laden Sie das Installationsabbild in Deploy hoch.

Nachdem Sie das ONTAP Select Installationsimage erworben haben, müssen Sie die Datei auf die virtuelle Deploy-Maschine hochladen.

.Bevor Sie beginnen
Sie müssen die Installationsabbilddatei auf Ihrem lokalen Rechner verfügbar haben. Sie müssen außerdem das Passwort für das Deploy-Administratorkonto haben.

.Informationen zu diesem Vorgang
In dieser Aufgabe wird eine Methode zum Hochladen der Datei auf die virtuelle Deploy-Maschine beschrieben. Möglicherweise gibt es andere Optionen, die für Ihre Umgebung besser geeignet sind.

.Schritt
. Laden Sie die Image-Datei in einer Befehlsshell auf Ihrer lokalen Workstation auf die virtuelle Maschine „Deploy“ hoch, wie in den folgenden Beispielen gezeigt:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Ergebnis
Die Knoteninstallationsdatei wird im Home-Verzeichnis des Administratorbenutzers gespeichert.



== Schritt 3: Installationsabbild hinzufügen

Fügen Sie das ONTAP Select Installationsabbild dem Verzeichnis „Deploy images“ hinzu, damit es bei der Bereitstellung eines neuen Clusters verfügbar ist.

.Bevor Sie beginnen
Sie müssen wissen, in welchem Verzeichnis die Installationsimagedatei auf der virtuellen Maschine des Bereitstellungsdienstprogramms abgelegt wurde. Es wird davon ausgegangen, dass sich die Datei im Home-Verzeichnis des Administrators befindet.

.Schritte
. Sign in .
. Starten Sie die Bash-Shell:


[listing]
----
shell bash
----
. Platzieren Sie die Installationsabbilddatei im Verzeichnis „images“, wie im folgenden Beispiel gezeigt:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Schritt 4: Verfügbare Installationsabbilder anzeigen

Zeigen Sie die ONTAP Select -Images an, die beim Bereitstellen eines neuen Clusters verfügbar sind.

.Schritte
. Greifen Sie auf der virtuellen Maschine des Bereitstellungsdienstprogramms auf die Webseite mit der Onlinedokumentation zu und melden Sie sich mit dem Administratorkonto (admin) an:
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Verwenden Sie den Domänennamen oder die IP-Adresse der virtuellen Bereitstellungsmaschine.

. Scrollen Sie zum Ende der Seite und wählen Sie *Deploy* und anschließend *GET /images*.
. Wählen Sie *Ausprobieren!*, um die verfügbaren ONTAP Select -Bilder anzuzeigen.
. Bestätigen Sie, dass das gewünschte Bild verfügbar ist.

