---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: Ab ONTAP Select 9.15.1 können Sie die Größe eines bestehenden Clusters erhöhen oder verringern. 
---
= Erweitern oder verkleinern Sie einen ONTAP Select Cluster auf einem ESXi- oder KVM-Host.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Clustergröße eines vorhandenen ONTAP Select Clusters für ESXi- und KVM-Hypervisor-Hosts erhöhen. Bei KVM-Hosts können Sie die Clustergröße von sechs auf acht Knoten erhöhen und von acht auf sechs Knoten verringern. Bei ESXi-Hosts erhöhen und verringern Sie die Clustergröße in Schritten zwischen sechs und zwölf Knoten.

Die folgenden Clustererweiterungen und -kontraktionen werden für ESXi- und KVM-Hosts nicht unterstützt:

* Erweiterungen von Clustern mit einem, zwei oder vier Knoten auf Cluster mit sechs oder acht Knoten.
* Kontraktionen von Clustern mit sechs oder acht Knoten auf Cluster mit einem, zwei oder vier Knoten.


[NOTE]
====
Um die Anzahl der Knoten in einem Cluster auf eine Größe zu ändern, die durch die Clustererweiterung oder -verkleinerung nicht unterstützt wird, müssen Sie die folgenden Aufgaben ausführen:

. Stellen Sie einen neuen Multi-Node-Cluster mithilfe von … bereit.link:task_cli_deploy_cluster.html["Befehlszeilenschnittstelle (CLI)"] oder dielink:task_deploy_cluster.html["Web-Benutzeroberfläche"] wird mit dem ONTAP Select Deploy-Verwaltungsprogramm bereitgestellt.
. Falls zutreffend, migrieren Sie die Daten mithilfe von [Name der Software/des Tools] in den neuen Cluster.link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["SnapMirror -Replikation"^] Die


====
Sie initiieren die Verfahren zur Clustererweiterung und -kontraktion von ONTAP Select Deploy über die CLI, API oder Weboberfläche.



== Überlegungen zu Hardware und Speicher

Die Funktion zur Clustererweiterung und -kontraktion wird auf den folgenden KVM- und ESXi-Hypervisor-Hosts unterstützt.

[role="tabbed-block"]
====
.ESXi
--
Ab ONTAP Select 9.15.1 wird die Clustererweiterung und -kontraktion auf ESXi-Hypervisor-Hosts unterstützt.

Die Clustererweiterung und -kontraktion wird für die folgenden ESXi-Hypervisor-Versionen unterstützt:

* ESXi 9.0
* ESXi 8.0 U3
* ESXi 8.0 U2
* ESXi 8.0 U1
* ESXi 8.0 GA
* ESXi 7.0 U3
* ESXi 7.0


--
.KVM
--
Ab ONTAP Select 9.17.1 wird die Clustererweiterung und -kontraktion auf KVM-Hypervisor-Hosts unterstützt.

Die Clustererweiterung und -kontraktion wird für die folgenden KVM-Hypervisor-Versionen unterstützt:

* Red Hat Enterprise Linux (RHEL) 64-bit 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 und 8.6
* Rocky Linux 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 und 8.6


[NOTE]
====
Für KVM-Hypervisoren auf RHEL 10.1 und 10.0 sowie Rocky Linux 10.1 und 10.0 Hosts gibt es Einschränkungen beim Software-RAID-Workflow. Weitere Informationen finden Sie in den folgenden Knowledge Base-Artikeln:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: Warnmeldung beim Erstellen der Cluster-Hardware unter Verwendung von RHEL 10 und ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: Speicherpools und Speicherdatenträger werden für SWR auf der Seite zur Clustererstellung auf Hosts mit RHEL10/Rocky 10 nicht angezeigt."^]


====
--
====


== Erweitern Sie den Cluster

Verwenden Sie die Clustererweiterungsfunktion, um die Größe eines vorhandenen ESXi- oder KVM-Clusters zu erhöhen.

[role="tabbed-block"]
====
.ESXi
--
Sie können die Größe eines vorhandenen ESXi-Clusters in den folgenden Schritten erhöhen:

* Von sechs Knoten auf acht, zehn oder zwölf Knoten
* Von acht Knoten auf zehn oder zwölf Knoten
* Von zehn auf zwölf Knoten


--
.KVM
--
Sie können die Größe eines vorhandenen KVM-Clusters von sechs auf acht Knoten erhöhen.

--
====
.Informationen zu diesem Vorgang
Zur Vorbereitung der Clustererweiterung werden neue ESXi- und KVM-Hosts in das Inventar aufgenommen und die Details der neuen Knoten zugewiesen. Vor dem Start der Clustererweiterung wird das ausgewählte interne Netzwerk durch eine Netzwerkvorprüfung überprüft.

.Bevor Sie beginnen
* Wenn Sie einen Cluster mit mehreren Knoten bereitstellen, sollten Sie mit der Netzwerkkonnektivitätsprüfung vertraut sein. Sie können den Netzwerkverbindungs-Checker mit folgendem Befehl ausführen:link:task_adm_connectivity.html["Web-Benutzeroberfläche"] oder dielink:task_cli_connectivity.html["Befehlszeilenschnittstelle (CLI)"] Die
* Stellen Sie sicher, dass Sie über die Lizenzdetails für die neuen Knoten verfügen.


.Schritte
. Sign in mit dem Administratorkonto bei der Web-Benutzeroberfläche des Bereitstellungsdienstprogramms an.
. Wählen Sie oben auf der Seite die Registerkarte *Cluster* und wählen Sie den gewünschten Cluster aus der Liste aus.
. Wählen Sie auf der Clusterdetailseite das Zahnradsymbol rechts auf der Seite und dann *Cluster erweitern* aus.
. Navigieren Sie zum Abschnitt *HA-Paar 4*.
. Wählen Sie die folgenden Konfigurationsdetails für Hochverfügbarkeitspaare (HA) für das vierte HA-Paar:
+
** Instanztyp
** Knotennamen
** Zugehörige Hypervisor-Hosts
** Knoten-IP-Adressen
** Lizenzen
** Netzwerkkonfiguration
** Speicherkonfiguration (RAID-Typ und Speicherpools)


. Wählen Sie *HA-Paar speichern*, um die Konfigurationsdetails zu speichern.
. Geben Sie die ONTAP -Anmeldeinformationen ein und wählen Sie *Cluster erweitern*.
. Wählen Sie *Weiter* und führen Sie die Netzwerkvorprüfung durch Auswahl von *Ausführen* aus.
+
Die Netzwerkvorprüfung bestätigt, dass das für den ONTAP Clusterverkehr ausgewählte interne Netzwerk ordnungsgemäß funktioniert.

. Wählen Sie *Cluster erweitern*, um den Clustererweiterungsprozess zu starten, und wählen Sie dann im Dialogfeld *OK*.
+
Die Erweiterung des Clusters kann bis zu 45 Minuten dauern.

. Überwachen Sie den mehrstufigen Clustererweiterungsprozess, um zu bestätigen, dass die Clustererweiterung erfolgreich war.
. Auf der Registerkarte *Ereignisse* finden Sie regelmäßige Updates zum Fortschritt der Operation. Die Seite wird in regelmäßigen Abständen automatisch aktualisiert.


.Nach Abschluss
link:task_cli_clusters.html["Sichern Sie die ONTAP Select Deploy-Konfigurationsdaten."].



== Kontrahieren Sie den Cluster

Verwenden Sie die Cluster-Kontraktionsfunktion, um die Größe eines vorhandenen ESXi- oder KVM-Clusters zu verringern.

[role="tabbed-block"]
====
.ESXi
--
Sie können die Größe eines vorhandenen ESXi-Clusters in den folgenden Schritten verringern:

* Von zwölf Knoten auf zehn, acht oder sechs Knoten
* Von zehn Knoten auf acht oder sechs Knoten
* Von acht auf sechs Knoten


--
.KVM
--
Sie können die Größe eines vorhandenen Clusters von acht auf sechs Knoten reduzieren.

--
====
.Informationen zu diesem Vorgang
Das gewünschte HA-Knotenpaar im Cluster wird ausgewählt, um die Clusterkontraktion während des Verfahrens vorzubereiten.

.Schritte
. Sign in mit dem Administratorkonto bei der Web-Benutzeroberfläche des Bereitstellungsdienstprogramms an.
. Wählen Sie oben auf der Seite die Registerkarte *Cluster* und wählen Sie den gewünschten Cluster aus der Liste aus.
. Wählen Sie auf der Clusterdetailseite das Zahnradsymbol rechts auf der Seite und dann *Vertragscluster* aus.
. Wählen Sie die HA-Paar-Konfigurationsdetails für jedes HA-Paar aus, das Sie entfernen möchten, und geben Sie die ONTAP Anmeldeinformationen ein. Wählen Sie dann *Vertragscluster* aus.
+
Es kann bis zu 30 Minuten dauern, bis der Cluster kontrahiert ist.

. Überwachen Sie den mehrstufigen Cluster-Kontraktionsprozess, um zu bestätigen, dass die Clusterkontraktion erfolgreich war.
. Auf der Registerkarte *Ereignisse* finden Sie regelmäßige Updates zum Fortschritt der Operation. Die Seite wird in regelmäßigen Abständen automatisch aktualisiert.

