---
sidebar: sidebar 
permalink: task_cli_deploy_cluster.html 
keywords: administer, administering, cli, create cluster, deploy cluster 
summary: Sie können die mit dem Verwaltungsdienstprogramm ONTAP Select Deploy bereitgestellte Befehlszeilenschnittstelle verwenden, um einen ONTAP Select Cluster mit einem oder mehreren Knoten zu erstellen. 
---
= Bereitstellen eines ONTAP Select Clusters mithilfe der CLI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die mit dem Verwaltungsdienstprogramm ONTAP Select Deploy bereitgestellte Befehlszeilenschnittstelle verwenden, um einen ONTAP Select Cluster mit einem oder mehreren Knoten zu erstellen.



== Schritt 1: Bereiten Sie die Bereitstellung vor

Bevor Sie einen ONTAP Select Cluster auf einem Hypervisor erstellen, sollten Sie die erforderlichen Vorbereitungen verstehen.

.Schritte
. Bereiten Sie das Anschließen von Speicher an den ONTAP Select Knoten vor
+
[role="tabbed-block"]
====
.Hardware-RAID
--
Wenn Sie einen lokalen Hardware-RAID-Controller verwenden, müssen Sie mindestens einen Datenspeicher (ESX) oder einenlink:kvm-host-configuration-and-preparation-checklist.html#step-2-create-a-storage-pool["Speicherpool (KVM)"] an jedem Knoten für die Systemdaten sowie die Wurzel und die Datenaggregate. Sie müssen den Speicherpool im Rahmen der Konfiguration des ONTAP Select Knotens anhängen.

--
.Software-RAID
--
Wenn Sie Software-RAID verwenden, müssen Sie mindestens einen Datenspeicher (ESX) oder einenlink:kvm-host-configuration-and-preparation-checklist.html#step-2-create-a-storage-pool["Speicherpool (KVM)"] für die Systemdaten und stellen Sie sicher, dass die SSD-Laufwerke für das Stammverzeichnis und die Datenaggregate verfügbar sind. Sie müssen den Speicherpool und die Festplatten im Rahmen der Konfiguration des ONTAP Select Knotens anhängen.

--
====
. Verfügbare ONTAP Select -Versionen
+
Das Deploy-Verwaltungsprogramm enthält eine einzige Version von ONTAP Select. Wenn Sie Cluster mit einer früheren Version von ONTAP Select bereitstellen möchten, müssen Sie zuerstlink:task_cli_deploy_image_add.html["Fügen Sie das ONTAP Select Image hinzu"] zu Ihrer Deploy-Instanz.

. Lizenzieren Sie ONTAP Select für eine Produktionsbereitstellung
+
Bevor Sie einen ONTAP Select Cluster in einer Produktionsumgebung einsetzen, müssen Sie eine Speicherkapazitätslizenz erwerben und die zugehörige Lizenzdatei herunterladen. Du kannstlink:concept_lic_production.html["Lizenzieren Sie den Speicher an jedem Knoten"] entweder mithilfe des _Capacity Tiers_-Modells oder durch Lizenzierung eines gemeinsam genutzten Pools mithilfe des _Capacity Pools_-Modells.





== Schritt 2: Hochladen und Registrieren einer Lizenzdatei

Nachdem Sie eine Lizenzdatei mit Speicherkapazität erworben haben, müssen Sie die Datei mit der Lizenz auf die virtuelle Deploy-Maschine hochladen und registrieren.


NOTE: Wenn Sie einen Cluster nur zur Evaluierung bereitstellen, können Sie diesen Schritt überspringen.

.Bevor Sie beginnen
Sie müssen über das Kennwort für das Administrator-Benutzerkonto verfügen.

.Schritte
. Verwenden Sie in einer Befehlsshell auf Ihrer lokalen Arbeitsstation das SFTP-Dienstprogramm, um die Lizenzdatei auf die virtuelle Deploy-Maschine hochzuladen.
+
Beispielausgabe

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put NLF-320000nnn.txt
exit
....
. Sign in .
. Registrieren Sie die Lizenz:
+
[source, cli]
----
license add -file-name <file_name>
----
+
Geben Sie das Kennwort des Administratorkontos ein, wenn Sie dazu aufgefordert werden.

. Zeigen Sie die Lizenzen im System an, um zu bestätigen, dass die Lizenz ordnungsgemäß hinzugefügt wurde:
+
[source, cli]
----
license show
----




== Schritt 3: Hypervisor-Hosts hinzufügen

Sie müssen jeden Hypervisor-Host registrieren, auf dem ein ONTAP Select Knoten ausgeführt wird.

[role="tabbed-block"]
====
.KVM
--
Sie müssen einen Hypervisor-Host registrieren, auf dem der ONTAP Select Knoten ausgeführt wird. Dabei authentifiziert sich das Deploy-Verwaltungsprogramm beim KVM-Host.

.Informationen zu diesem Vorgang
Wenn mehr als ein Hypervisor-Host benötigt wird, verwenden Sie dieses Verfahren, um jeden Host hinzuzufügen.

.Schritte
. Sign in mit dem Administratorkonto per SSH bei der CLI des Bereitstellungsdienstprogramms an.
. Registrieren Sie den Host:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type KVM -username <KVM_username>
----
+
Beispielausgabe

+
[listing]
----
host register -name 10.234.81.14 -hypervisor-type KVM -username root
----
+
Geben Sie das Kennwort für das Hostkonto ein, wenn Sie dazu aufgefordert werden.

. Zeigen Sie den Status des Hosts an und bestätigen Sie, dass er authentifiziert ist:
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
Beispielausgabe

+
[listing]
----
host show -name 10.234.81.14 -detailed
----


--
.ESXi
--
Dabei authentifiziert sich das Deploy-Verwaltungsprogramm entweder beim vCenter-Server, der den Host verwaltet, oder direkt beim eigenständigen ESXi-Host.

.Informationen zu diesem Vorgang
Bevor Sie einen von vCenter verwalteten Host registrieren, müssen Sie ein Verwaltungsserverkonto für den vCenter-Server hinzufügen. Wenn der Host nicht von vCenter verwaltet wird, können Sie die Hostanmeldeinformationen bei der Registrierung angeben. Gehen Sie wie folgt vor, um jeden Host hinzuzufügen.

.Schritte
. Sign in mit dem Administratorkonto per SSH bei der CLI des Bereitstellungsdienstprogramms an.
. Wenn der Host von einem vCenter-Server verwaltet wird, fügen Sie die Anmeldeinformationen des vCenter-Kontos hinzu:
+
[source, cli]
----
credential add -hostname <FQDN|IP> -type vcenter -username <vcenter_username>
----
+
Beispielausgabe

+
....
credential add -hostname vc.select.company-demo.com -type vcenter -username administrator@vsphere.local
....
. Registrieren Sie den Host:
+
** Registrieren Sie einen eigenständigen Host, der nicht von vCenter verwaltet wird:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -username <esx_username>
----
** Registrieren Sie einen von vCenter verwalteten Host:
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -mgmt-server <FQDN|IP>
----
+
Beispielausgabe

+
....
host register -name 10.234.81.14 -hypervisor-type ESX -mgmt-server vc.select.company-demo.com
....


. Zeigen Sie den Status des Hosts an und bestätigen Sie, dass er authentifiziert ist.
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
Beispielausgabe

+
....
host show -name 10.234.81.14 -detailed
....


--
====


== Schritt 4: Erstellen und Konfigurieren eines ONTAP Select Clusters

Sie müssen den ONTAP Select Cluster erstellen und anschließend konfigurieren. Nach der Konfiguration des Clusters können Sie die einzelnen Knoten konfigurieren.

.Bevor Sie beginnen
Entscheiden Sie, wie viele Knoten der Cluster enthält, und legen Sie die zugehörigen Konfigurationsinformationen bereit.

.Informationen zu diesem Vorgang
Beim Erstellen eines ONTAP Select Clusters generiert das Deploy-Dienstprogramm automatisch die Knotennamen basierend auf dem von Ihnen angegebenen Clusternamen und der Knotenanzahl. Deploy generiert außerdem die eindeutigen Knotenkennungen.

.Schritte
. Sign in mit dem Administratorkonto per SSH bei der CLI des Bereitstellungsdienstprogramms an.
. Erstellen Sie den Cluster:
+
[source, cli]
----
cluster create -name <cluster_name> -node-count <count>
----
+
Beispielausgabe

+
....
cluster create -name test-cluster -node-count 1
....
. Konfigurieren Sie den Cluster:
+
[source, cli]
----
cluster modify -name <cluster_name> -mgmt-ip <IP_address> -netmask <netmask> -gateway <IP_address> -dns-servers <FQDN|IP>_LIST -dns-domains <domain_list>
----
+
Beispielausgabe

+
....
cluster modify -name test-cluster -mgmt-ip 10.234.81.20 -netmask 255.255.255.192
-gateway 10.234.81.1 -dns-servers 10.221.220.10 -dnsdomains select.company-demo.com
....
. Zeigen Sie die Konfiguration und den Status des Clusters an:
+
[source, cli]
----
cluster show -name <cluster_name> -detailed
----




== Schritt 5: Konfigurieren eines ONTAP Select Knotens

Sie müssen jeden Knoten im ONTAP Select Cluster konfigurieren.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie über die Konfigurationsinformationen für den Knoten verfügen.
* Stellen Sie sicher, dass die Lizenzdatei für die Kapazitätsstufe oder den Kapazitätspool hochgeladen und im Bereitstellungsprogramm installiert wurde.


.Informationen zu diesem Vorgang
Sie sollten dieses Verfahren verwenden, um jeden Knoten zu konfigurieren. In diesem Beispiel wird auf den Knoten eine Capacity Tier-Lizenz angewendet.

.Schritte
. Sign in mit dem Administratorkonto per SSH bei der CLI des Bereitstellungsdienstprogramms an.
. Bestimmen Sie die den Clusterknoten zugewiesenen Namen:
+
[source, cli]
----
node show -cluster-name <cluster_name>
----
. Wählen Sie den Knoten aus und führen Sie die Grundkonfiguration durch:
+
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -host-name <FQDN|IP> -license-serial-number <number> -instance-type TYPE -passthrough-disks false
----
+
Beispielausgabe

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -host-name 10.234.81.14
-license-serial-number 320000nnnn -instance-type small -passthrough-disks false
....
+
Die RAID-Konfiguration für den Knoten wird mit dem Parameter _passthrough-disks_ angegeben. Wenn Sie einen lokalen Hardware-RAID-Controller verwenden, muss dieser Wert „false“ sein. Wenn Sie Software-RAID verwenden, muss dieser Wert „true“ sein.

+
Für den ONTAP Select Knoten wird eine Capacity Tier-Lizenz verwendet.

. Zeigen Sie die auf dem Host verfügbare Netzwerkkonfiguration an:
+
[source, cli]
----
host network show -host-name <FQDN|IP> -detailed
----
+
Beispielausgabe

+
....
host network show -host-name 10.234.81.14 -detailed
....
. Führen Sie die Netzwerkkonfiguration des Knotens durch:
+
[role="tabbed-block"]
====
.ESXi-Host
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-networks <network_name> -data-networks <network_name> -internal-network <network_name>
----
--
.KVM-Host
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-vlans <vlan_id> -data-vlans <vlan_id> -internal-vlans <vlad_id>
----
--
====
+
Wenn Sie einen Einzelknotencluster bereitstellen, benötigen Sie kein internes Netzwerk und sollten „-internal-network“ entfernen.

+
Beispielausgabe

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -mgmt-ip 10.234.81.21
-management-networks sDOT_Network -data-networks sDOT_Network
....
. Zeigen Sie die Konfiguration des Knotens an:
+
[source, cli]
----
node show -name <node_name> -cluster-name <cluster_name> -detailed
----
+
Beispielausgabe

+
....
node show -name test-cluster-01 -cluster-name test-cluster -detailed
....




== Schritt 6: Speicher an die ONTAP Select Knoten anhängen

Konfigurieren Sie den von jedem Knoten im ONTAP Select Cluster verwendeten Speicher. Jedem Knoten muss immer mindestens ein Speicherpool zugewiesen sein. Bei Verwendung von Software-RAID muss jedem Knoten außerdem mindestens ein Festplattenlaufwerk zugewiesen sein.

.Bevor Sie beginnen
Erstellen Sie den Speicherpool mit VMware vSphere. Wenn Sie Software-RAID verwenden, benötigen Sie außerdem mindestens ein freies Festplattenlaufwerk.

.Informationen zu diesem Vorgang
Wenn Sie einen lokalen Hardware-RAID-Controller verwenden, müssen Sie die Schritte 1 bis 4 ausführen. Wenn Sie Software-RAID verwenden, müssen Sie die Schritte 1 bis 6 ausführen.

.Schritte
. Sign in .
. Zeigen Sie die auf dem Host verfügbaren Speicherpools an:
+
[source, cli]
----
host storage pool show -host-name <FQDN|IP>
----
+
Beispielausgabe

+
[listing]
----
host storage pool show -host-name 10.234.81.14
----
+
Sie können die verfügbaren Speicherpools auch über VMware vSphere beziehen.

. Fügen Sie einen verfügbaren Speicherpool an den ONTAP Select Knoten an:
+
[source, cli]
----
node storage pool attach -name <pool_name> -cluster-name <cluster_name> -node-name <node_name> -capacity-limit <limit>
----
+
Wenn Sie den Parameter „-capacity-limit“ einschließen, geben Sie den Wert als GB oder TB an.

+
Beispielausgabe

+
[listing]
----
node storage pool attach -name sDOT-02 -cluster-name test-cluster -
node-name test-cluster-01 -capacity-limit 500GB
----
. Zeigen Sie die an den Knoten angeschlossenen Speicherpools an:
+
[source, cli]
----
node storage pool show -cluster-name <cluster_name> -node-name <node_name>
----
+
Beispielausgabe

+
[listing]
----
node storage pool show -cluster-name test-cluster -node-name testcluster-01
----
. Wenn Sie Software-RAID verwenden, schließen Sie das bzw. die verfügbare(n) Laufwerk(e) an:
+
[source, cli]
----
node storage disk attach -node-name <node_name> -cluster-name <cluster_name> -disks <list_of_drives>
----
+
Beispielausgabe

+
[listing]
----
node storage disk attach -node-name NVME_SN-01 -cluster-name NVME_SN -disks 0000:66:00.0 0000:67:00.0 0000:68:00.0
----
. Wenn Sie Software-RAID verwenden, zeigen Sie die an den Knoten angeschlossenen Festplatten an:
+
[source, cli]
----
node storage disk show -node-name <node_name> -cluster-name <cluster_name>`
----
+
Beispielausgabe

+
[listing]
----
node storage disk show -node-name sdot-smicro-009a -cluster-name NVME
----




== Schritt 7: Bereitstellen eines ONTAP Select Clusters

Nachdem der Cluster und die Knoten konfiguriert wurden, können Sie den Cluster bereitstellen.

.Bevor Sie beginnen
Führen Sie die Netzwerkverbindungsprüfung mit folgendem Befehl aus:link:task_adm_connectivity.html["Web-Benutzeroberfläche"] oder dielink:task_cli_connectivity.html["Befehlszeilenschnittstelle (CLI)"] um die Konnektivität zwischen den Clusterknoten im internen Netzwerk zu bestätigen.

.Schritte
. Sign in mit dem Administratorkonto per SSH bei der CLI des Bereitstellungsdienstprogramms an.
. Stellen Sie den ONTAP Select Cluster bereit:
+
[source, cli]
----
cluster deploy -name <cluster_name>
----
+
Beispielausgabe

+
[listing]
----
cluster deploy -name test-cluster
----
+
Geben Sie bei entsprechender Aufforderung das Kennwort für das ONTAP Administratorkonto ein.

. Zeigen Sie den Status des Clusters an, um festzustellen, wann er erfolgreich bereitgestellt wurde:
+
[source, cli]
----
cluster show -name <cluster_name>
----


.Wie geht es weiter?
link:task_cli_clusters.html["Sichern Sie die ONTAP Select Deploy-Konfigurationsdaten."].
